<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
        <PackageReference Include="Avalonia" Version="11.3.11" />
        <PackageReference Include="SemanticVersioning" Version="3.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>
