<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <PluginId>ProjectAFS.Template.StandardFanmadeProject</PluginId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProjectAFS.Core\ProjectAFS.Core.csproj">
          <Private>false</Private>
          <ExcludeAssets>runtime</ExcludeAssets>
      </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\TemplateProject.afsproj" />
      <None Update="plugin.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    
    <Import Project="..\Build\PluginPacking.targets" />
    <Import Project="..\Build\PluginAutoCopy.targets" />

</Project>